using System;
using System.Collections.Generic;

namespace Database.Data.Models
{
    public partial class Expenses
    {
        public int ExpenseId { get; set; }
        public Guid AdvisorFirmId { get; set; }
        public Guid ContactId { get; set; }
        public int ExpenseType { get; set; }
        public int ExpenseOwner { get; set; }
        public string ExpenseDescription { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public decimal AnnualExpense { get; set; }
        public decimal MonthlyExpense { get; set; }
        public bool MoreInfoRequired { get; set; }
        public int? InstitutionId { get; set; }
        public string CalculationDetails { get; set; }
        public bool AutoGenerated { get; set; }

        public virtual AdvisorFirms AdvisorFirm { get; set; }
        public virtual Contacts Contact { get; set; }
        public virtual Institutions Institution { get; set; }
    }
}
